### ISSUE TITLE
left arrow issue

### ISSUE THREAD

**Issue by 532910** [Toxblh/youtube-speed-control#1]
![image](https://user-images.githubusercontent.com/14617699/85131490-96beec80-b23f-11ea-8cc0-7f2a089289fc.png)

ff 77 debian sid

**Comment by Toxblh** [comment]
Do you use zoom on page?

**Comment by 532910** [comment]
Nope, it is 100%

**Comment by Toxblh** [comment]
All should be fixed in version 1.0.1 (soon will approve)

**Comment by 532910** [comment]
Works fine now, even scaled up.
