### ISSUE TITLE
Chrome extension in Google store

### ISSUE THREAD

**Issue by jcubic** [Toxblh/youtube-speed-control#10]
I'm not sure if you're aware but your plugin is in Chrome store:

https://chrome.google.com/webstore/detail/youtube-playback-speed-co/hdannnflhlmdablckfkjpleikpphncik

The code is minified for no reason and author added donation feature.

**Comment by jcubic** [comment]
I was searching for the source code because I wanted to change something.

**Comment by Toxblh** [comment]
It is two different projects:) my only for firefox

**Comment by jcubic** [comment]
It looks like modification of you project, even screenshots, icon and name are the same, it looks like there are minor differences between FF and Chrome, I was able to install your project in chrome. It's looks like he use your project as base without attribution.
