### ISSUE TITLE
It has stopped working

### ISSUE THREAD

**Issue by RonaldBolado** [Toxblh/youtube-speed-control#13]
When you change speed, it goes all the way to 16x automatically. No fine tuning. Already tried reinstalling, not sure what's happening.

**Comment by RonaldBolado** [comment]
Uhhh suddenly it started working again, not sure what happened now either. Sorry lol.

**Comment by Stromae11** [comment]
I still have the same problem. When I try to change speed it goes to 16x or 0x.

**Comment by MBZ-07** [comment]
The same for me, she got to 16x suddenly, then it doesn't work anymore, even when i tried to install older version.

**Comment by MBZ-07** [comment]
Please, fix the + and - keys, they're not working anymore!

**Comment by Toxblh** [comment]
which version OS, Firefox and plugin?

**Comment by Stromae11** [comment]
Windows 10 (2004 / 19041.572), Firefox 59.0.3, plugin version 1.1.0

**Comment by MBZ-07** [comment]
Ubuntu 20.04, Firefox 82.0(64 bit), Plugin v1.0.2

**Comment by RonaldBolado** [comment]
windows 7

firefox 82.0.2 (64-bit)

1.1.0

**Comment by GarrettStrahan** [comment]
windows 7, everything is up to date. goes to x16 or 0 speed. Does not let me go beyond 2.0x speed unless its x16 speed. The hotkeys dont work correctly.

**Comment by Toxblh** [comment]
Please to try version 1.1.1 will this fixed or not?

**Comment by Stromae11** [comment]
Version 1.1.2. Problem isn't fixed.

**Comment by Toxblh** [comment]
So. I don't know what is problem, I'm fully check all input parameters and if it happens looks like JS don't work correctly. I tried to catch with all my machines and I can't to find the problem. If you can - please provide a PR or information where is problem.

**Comment by Toxblh** [comment]
Confirmed on Windows 10.

**Comment by MBZ-07** [comment]
After the plugin got upadated, the keys are not working anymore, even the
previous versions are not working properly now.

**Comment by Toxblh** [comment]
Fixed increase/decrease speed. If you have a problem with increase to 16x and decrease to 0x, please reset settings of addon in option page via click on icon in URL address of youtube page or via addons setting in browser menu.
