### ISSUE TITLE
Speed is return to x1.0 in ESR Firefox every new tab/refresh page

### ISSUE THREAD

**Issue by SymphonySimper** [Toxblh/youtube-speed-control#16]
It would be nice, if you add an option to set a default speed

**Comment by Toxblh** [comment]
What you mean? Just click to number will set x1.0, one else, return to set before

**Comment by SymphonySimper** [comment]
I'm meant like I usually watch videos at 2x, but I feel like some even 2x is slow. So I want my playback speed to be 3x all the time.

**Comment by Toxblh** [comment]
So just increase it upper. Firefox support x4 with sound and x16 without

**Comment by SymphonySimper** [comment]
Yeah I know, what happens is when you refresh the page it resets back to 1x then I have to manually increase it back to 2x/3x

**Comment by Toxblh** [comment]
@SymphonySimper I self use the plugin and don't see the behaviour. I set speed once and this is apply all new video's. It's not sync across opened tabs, but new videos will use last set video speed. 
btw it's easy to change via + and - buttons.

**Comment by Toxblh** [comment]
Also from reviews I found the bug #14 maybe is it the same?

**Comment by SymphonySimper** [comment]
> 

Sadly its not the same

**Comment by SymphonySimper** [comment]
FF version: Mozilla Firefox 91.5.0esr
OS: Gentoo
What I'm trying to say is to have an option to set speed in options page.

**Comment by Toxblh** [comment]
Ok I'll try to replay in the system.
`firefox-bin` or compiled self?

**Comment by Toxblh** [comment]
Ok, yeah it's replay even in macOS ESR. Awesome. I will see. Thank you

**Comment by Toxblh** [comment]
@SymphonySimper 
Could you please to check the settings and don't forget to save it! 
`Remember Playback Speed For All Videos`
![image](https://user-images.githubusercontent.com/2198153/151833633-febebf68-40a4-4a46-919a-7151b3865163.png)

**Comment by SymphonySimper** [comment]
Yeah it works great!, Thanks a lot.

But this doesn't work if you have set default playback speed with [Enhancer for YouTube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/). So can you add a section in readme to tell people to do so?

**Comment by Toxblh** [comment]
Wow. Thx. I never try to test with different plugins. Ok I’ll add it to description and readme.
