### ISSUE TITLE
Controller keeps disappearing, have to reinstall several times a day

### ISSUE THREAD

**Issue by choi403** [Toxblh/youtube-speed-control#19]
Hi, I'm using Windows 10 Version 21H2 (Build 19044.1766), Chrome 102.0.5005.115 64-bit (stable) and recently the extension stopped working. 

One day I found out that the controller on the video disappeared and the shortcuts didn't work, so I removed the extension and reinstalled it from the chrome web store, refreshed the youtube page and the controller was back, with all the shortcuts working, but only for a short moment. 

After like half an hour the controller was gone again, so I had to reinstall it again, and under 30 minutes it happened once more. I was wondering if there's a way to fix this.

**Comment by Toxblh** [comment]
But... This is firefox extension 😅
Chrome is not my.
