### ISSUE TITLE
[Chrome] Console deprecation warning about synchronous DOMNodeInserted

### ISSUE THREAD

**Issue by igorsantos07** [Toxblh/youtube-speed-control#23]
This error is a bit annoying for developers and was reported a couple of weeks ago in the Chrome Webstore:

inject.js:1 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by Toxblh** [comment]
Chrome that is diff plugin - my is only for Firefox
