### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [Toxblh/youtube-speed-control#8]
Hi

https://addons.mozilla.org/en-GB/firefox/addon/youtube-speed-control/versions/1.0.2/updateinfo/ is empty and so release notes can not be seen at `about:addons` when deciding whether to accept an update. 

For now, I see https://github.com/Toxblh/youtube-speed-control/commits/master

For future releases, can you provide notes at AMO? Thanks

**Comment by Toxblh** [comment]
Hi. Okay, I found how to do that. :) 
Updated for prev releases. Will provide for future

**Comment by grahamperrin** [comment]
Thanks 👍

![image](https://user-images.githubusercontent.com/192271/92301946-d99b8100-ef5f-11ea-85e3-a9c2b2b4d27b.png)
